feat: implement claimMany wrapper
graphprotocol/indexer pull request #260
Opened 2021-06-24 20:15 UTC by chriswessels

2021-08-23 23:43 UTC, fordN commented on packages/indexer-agent/src/network.ts
> +      const parsedAllocs: Allocation[] = result.data.allocations.map(parseGraphQLAllocation)
Move this below the next block so it only executes if the batch value is above the threshold?

2021-08-23 23:47 UTC, fordN commented on packages/indexer-agent/src/network.ts
> +    const logger = this.logger.child({
I would move the allocations property out of this logger instantiation and instead include it in the `Claim tokens from the rebate pool for many allocations` log message. I think it'll be unnecessarily verbose to include entire allocations list in the subsequent log lines that are for specific allocations.

2021-08-23 23:52 UTC, fordN commented on packages/indexer-agent/src/commands/start.ts
> +      .option('voucher-redeem-min-single-value', {
Do you think we can simplify the configs by combining 'voucher-redeem-min-single-value' and 'rebate-claim-min-single-value'?  That is what we currently do, but I suppose some indexers may want to redeem vouchers even though they won't necessarily claim the rebate.

2021-08-23 23:56 UTC, fordN commented on packages/indexer-agent/src/commands/start.ts
> +      .option('rebate-claim-min-single-value', {
Can we simplify this argument name a bit?  

Maybe `rebate-claim-min` and then its batch counterpart would be `rebate-claim-batch-min`?  Another option I've used here in the past is `threshold` which would make it `rebate-claim-threshold` and `rebate-claim-batch-threshold`.

2021-08-24 00:02 UTC, fordN commented on packages/indexer-agent/src/network.ts
> +      logger.info(`Successfully claimed allocations`, { claimedAllocations: allocationIds })
Include the count of allocations claimed?  
```
logger.info(`Successfully claimed ${allocationIds.length} allocations`, { claimedAllocations: allocationIds })
```

2021-08-24 00:08 UTC, fordN requested changes
Nice! I know you marked this as draft, but it appears close to being ready to merge. I left a few questions and requests in the review comments.

2021-11-17 13:52 UTC, chriswessels commented
lgtm!

2021-11-17 15:17 UTC, merged