indexer-agent: fix gas price in tx management logs
graphprotocol/indexer pull request #392
Opened 2022-03-17 13:24 UTC by chriswessels

Fixes logs like this:
```{"level":30,"time":1647523071123,"pid":1,"hostname":"99c572502af3","name":"IndexerAgent","component":"Network","indexer":"0x365507a4eEF5341cF00340F702F7f6E74217d96e","operator":"0x0EBAB0EB90E97DD211Aa5D4fb19E7048ae4aa4e5","allocation":"0x1B6551918c4175eCB82bA1191857ad5D4C751E27","deployment":{"bytes32":"0x45a6851c2f977fc91a390eb6f4c67a035296581244bc83cf8b74c5371f438436","ipfsHash":"QmT2Y7SHXGRt7EKXzFPYMjnrgX64PQr86EjbsHoDLNzwLy"},"createdAtEpoch":438,"poi":"0x53b8688603062200577d77eb5af515bf346b709d0d5dee11860cff936e5120c4","createdAtBlockHash":"0x7d6fcb374cafbe4c9fa30ac7cfe50a38c91fb68667e82f6b4182ebbc94bef6fc","action":"close","maxBaseFeePerGas":100000000000,"baseFeePerGas":{"type":"BigNumber","hex":"0x357dea1405"},"priceEstimateAttempt":6,"msg":"Base gas fee per gas estimation still above max threshold"}```

2022-03-17 20:05 UTC, hopeyen approved these changes
👍

2022-03-28 19:29 UTC, fordN requested changes

2022-03-28 19:29 UTC, fordN commented on packages/indexer-agent/src/network.ts
> +                currentGasPriceEstimate: feeData.gasPrice.toNumber(),
I believe you need a non-null assertion here, so it would be `feeData.gasPrice!.toNumber()`

2022-03-28 19:29 UTC, fordN commented on packages/indexer-agent/src/network.ts
> +              currentGasPriceEstimate: feeData.gasPrice.toNumber(),
Here as well.

2024-07-12 16:40 UTC, fordN commented
@chriswessels been about 2 years here in review 😬. I'm going to just pick this one up and finish it.

2024-07-12 17:55 UTC, fordN commented
Closing in favor of #954

2024-07-12 17:55 UTC, closed without merging