Update feature support matrix to include Fantom and Polygon
graphprotocol/indexer pull request #655
Opened 2023-04-28 10:54 UTC by PedroMD

Proposing adding support for Fantom and Polygon to the feature support matrix. This PR will be included in the GGP (Graph Governance Proposal) to be created here https://snapshot.org/#/council.graphprotocol.eth.

This PR should be merged after Council approval. Afterward, the reference to the canonical GGP-ratified feature support matrix (end of the .md) will be updated.

2023-05-04 15:02 UTC, PedroMD commented
@fordN I just noticed we also have https://github.com/graphprotocol/indexer/blob/main/docs/feature-support-matrix.md 
I there a reason why we have the matrix in two different .md files? Shouldn't we have a canonical one we can reference in GGPs to be ratified by the Council? 

And while I'm at it, is this the process we want to continue to follow? Would it make sense to, for instance, have the latest ratified feature matrix anchored on-chain in a DataEdge type of contract and indexed by the network subgraph or something like that?

2023-05-22 00:46 UTC, PedroMD commented
Now that the Council [has ratified it](https://snapshot.org/#/council.graphprotocol.eth/proposal/0x56d75d710d3f90a96705f455628e1309666aa2eb280f5c4295291ca3728c3ed0), this one is ready to be merged. However, I believe we should have only 1 instance of this feature matrix for both Ethereum and Arbitrum and not multiple as we currently have (in `docs/feature-support-matrix.md` and `mainnet.md`). How we structure docs for different mainnet and testnet environments may also affect this. Payne is already proposing breaking it down into multiple files: https://github.com/graphprotocol/indexer/pull/660

@fordN , should we close this one for now and decide then how we want to structure these docs?

2023-06-01 17:46 UTC, azf20 requested changes
I think the live alias is `matic`?

2023-06-01 17:51 UTC, PedroMD commented on docs/networks/mainnet.md
> +| eip155:137               | polygon      | Yes         | Yes          | Yes               | Yes                  | Yes              |
Oh, yes, it recently changed to `matic`. I'll update it

2023-06-05 11:39 UTC, azf20 approved these changes

2023-06-05 15:08 UTC, merged