indexer-common: Avoid using createdAt field for pagination
graphprotocol/indexer pull request #914
Opened 2024-06-17 22:02 UTC by fordN

## Changes
- Update several `NetworkMonitor` functions to paginate by `id` instead of by `createdAt`. Functions updated: subgraphs(), subgraphDeployments() and disputableAllocations(). On L2 networks, like arbitrum-one, `createdAt` is not necessarily unique.

2024-06-17 22:34 UTC, dwerner approved these changes
lgtm! thanks

2024-06-17 23:44 UTC, aasseman requested changes
Just nitpicking on adhering to the subgraph's schema, though graph-node may currently allow these things.

Also, somewhat unrelated, I found a few places in the code where pagination isn't implemented at all. In particular that could cause issues if somehow an indexer managed to open more than 1000 allocations. We know that some indexers are already indexing more than 1000 subgraphs at a time, so it's not completely impossible.

2024-06-17 23:44 UTC, aasseman commented on packages/indexer-common/src/indexer-management/monitor.ts
> +      lastId: 0,
The network subgraph's schema is using type `ID` for ids, which is an alias for `string`.
(see https://semiotic-ai.slack.com/archives/C032EDF093K/p1713996760318369?thread_ts=1713983989.035979&cid=C032EDF093K)

```suggestion
      lastId: '',
```

2024-06-17 23:44 UTC, aasseman commented on packages/indexer-common/src/indexer-management/monitor.ts
> +            query subgraphs($first: Int!, $lastId: Int!, $subgraphs: [String!]!) {
```suggestion
            query subgraphs($first: Int!, $lastId: ID!, $subgraphs: [String!]!) {
```

2024-06-17 23:44 UTC, aasseman commented on packages/indexer-common/src/indexer-management/monitor.ts
> +            query subgraphDeployments($first: Int!, $lastId: Int!) {
```suggestion
            query subgraphDeployments($first: Int!, $lastId: ID!) {
```

2024-06-17 23:44 UTC, aasseman commented on packages/indexer-common/src/indexer-management/monitor.ts
>              ) {
This is missing the variable declaration for `$lastId`. 
`graph-node` may let it pass, but I think that The Guild is/was working on making graph-node stricter wrt. the GraphQL spec, which could cause issues in the future.

2024-06-24 23:12 UTC, dwerner commented
Removing my approval as I've made changes now.

2024-06-25 00:25 UTC, aasseman requested changes
One of the comments was not addressed. GitHub won't let me explicitly select the piece of code....

So here's the issue:
`packages/indexer-common/src/indexer-management/monitor.ts:1139` `$createdAt: Int!` should be `$lastId: ID!`

2024-06-25 15:37 UTC, dwerner commented
> One of the comments was not addressed. GitHub won't let me explicitly select the piece of code....
> 
> So here's the issue: `packages/indexer-common/src/indexer-management/monitor.ts:1139` `$createdAt: Int!` should be `$lastId: ID!`

Thanks for catching this.

2024-06-25 16:54 UTC, aasseman approved these changes

2024-06-27 22:29 UTC, dwerner approved these changes
Looks good to me.

2024-06-28 15:06 UTC, merged